import { User, Property, Commission, Activity } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    memberId: 'ADMIN001',
    name: 'Admin User',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
  },
  {
    id: '2',
    memberId: 'MEMBER001',
    name: 'Ali Rezaei',
    role: 'member',
    parentId: '1',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=member1',
  },
  {
    id: '3',
    memberId: 'MEMBER002',
    name: 'Sara Mohammadi',
    role: 'member',
    parentId: '2',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=member2',
  },
  {
    id: '4',
    memberId: 'MEMBER003',
    name: 'Reza Ahmadi',
    role: 'member',
    parentId: '2',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=member3',
  },
  {
    id: '5',
    memberId: 'MEMBER004',
    name: 'Maryam Hosseini',
    role: 'member',
    parentId: '1',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=member4',
  },
];

export const mockProperties: Property[] = [
  {
    id: '1',
    type: 'apartment',
    status: 'available',
    area: 120,
    elevator: true,
    parkingSpots: 2,
    rooms: 3,
    yearBuilt: 2020,
    age: 4,
    images: [
      'https://picsum.photos/seed/prop1/800/600',
      'https://picsum.photos/seed/prop1b/800/600',
    ],
    ownerId: '2',
    price: 2500000000,
    description: 'Luxury apartment in northern Tehran',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: '2',
    type: 'villa',
    status: 'pending',
    area: 350,
    elevator: false,
    parkingSpots: 4,
    rooms: 5,
    yearBuilt: 2018,
    age: 6,
    images: [
      'https://picsum.photos/seed/prop2/800/600',
      'https://picsum.photos/seed/prop2b/800/600',
    ],
    ownerId: '2',
    price: 8500000000,
    description: 'Beautiful villa with garden',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: '3',
    type: 'commercial',
    status: 'sold',
    area: 80,
    elevator: true,
    parkingSpots: 1,
    rooms: 2,
    yearBuilt: 2015,
    age: 9,
    images: [
      'https://picsum.photos/seed/prop3/800/600',
    ],
    ownerId: '3',
    price: 4500000000,
    commission: 45000000,
    description: 'Commercial unit in city center',
    createdAt: new Date('2023-11-10'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: '4',
    type: 'land',
    status: 'available',
    area: 500,
    elevator: false,
    parkingSpots: 0,
    rooms: 0,
    yearBuilt: 2024,
    age: 0,
    images: [
      'https://picsum.photos/seed/prop4/800/600',
    ],
    ownerId: '4',
    price: 12000000000,
    description: 'Land for development',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: '5',
    type: 'apartment',
    status: 'rented',
    area: 95,
    elevator: true,
    parkingSpots: 1,
    rooms: 2,
    yearBuilt: 2022,
    age: 2,
    images: [
      'https://picsum.photos/seed/prop5/800/600',
      'https://picsum.photos/seed/prop5b/800/600',
    ],
    ownerId: '5',
    price: 1800000000,
    commission: 18000000,
    description: 'Modern apartment with city view',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-28'),
  },
];

export const mockCommissions: Commission[] = [
  {
    id: '1',
    propertyId: '3',
    memberId: '3',
    amount: 45000000,
    percentage: 1,
    status: 'paid',
    createdAt: new Date('2024-03-01'),
    paidAt: new Date('2024-03-10'),
  },
  {
    id: '2',
    propertyId: '5',
    memberId: '5',
    amount: 18000000,
    percentage: 1,
    status: 'pending',
    createdAt: new Date('2024-02-28'),
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'property_added',
    description: 'New apartment listed in northern Tehran',
    userId: '2',
    timestamp: new Date('2024-03-20'),
  },
  {
    id: '2',
    type: 'property_sold',
    description: 'Commercial unit sold for 4,500,000,000 IRR',
    userId: '3',
    timestamp: new Date('2024-03-01'),
  },
  {
    id: '3',
    type: 'commission_paid',
    description: 'Commission paid to Sara Mohammadi',
    userId: '3',
    timestamp: new Date('2024-03-10'),
  },
  {
    id: '4',
    type: 'member_added',
    description: 'New member Maryam Hosseini joined',
    userId: '5',
    timestamp: new Date('2024-03-15'),
  },
];